### ISSUE TITLE
Cannot find symbol "import static com.huawei.hms.maps.model.BitmapDescriptorFactory.sIBitmapDescriptorDelegate";

### ISSUE THREAD

**Issue by Maharshi01** [el173/react-native-hms#6]
Hi @el173 ,

Can you please remove this line from AirMapMarker.java file as it's causing my build to fail. I have read the huawei map kit docs, sIBitmapDescriptorDelegate method is not defined any where in BitmapDescriptorFactory interface. After commenting this line, was able to build without any issues. So, can you please remove this line as it's a show stopper for us.

![photo_2021-08-18_22-45-33](https://user-images.githubusercontent.com/48430425/129945152-9ff05391-4c99-4f62-90bc-6b1c6df285b1.jpg)

**Comment by el173** [comment]
Fixed in new release with your PR @Maharshi01 #7
